### ISSUE TITLE
页面编号 url 逻辑变化

### ISSUE THREAD

**Issue by SunnyBingoMe** [Rhilip/NSFC_conclusion_downloader#18]
downloader 显示 HTTP ERR 500，现在 url 末尾 类似 MD5 或 HAVAL-128，但都不是（或已加盐）。未能看出逻辑。

**Comment by Rhilip** [comment]
图片的url倒是能通过接口请求出来，但是申请号和现在新url的关系我也没找出来
http://output.nsfc.gov.cn/conclusionProject/0aa4360e4c30d63da66cb6768cd74e06

从检索接口来看，似乎直接在搜索的时候返回了这串 `0aa4360e4c30d63da66cb6768cd74e06` 新的id。
在没有新方法的情况下，是不是可以这样改逻辑：
输入上面哪个结题项目的地址，软件完成剩下的图片下载和pdf生成？
